name: Send advisory

on:
  push:
    branches: ['main']


env: # sendgrid api token
  sendgrid_api: ${{ secrets.SENDGRID_API }}

permissions:
  contents: read

jobs:
  send-modified-files:
    name: Send advisory files created in last hour
    runs-on: ubuntu-latest
    environment:
      name: communication
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout docs
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 2
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Send advisories
        run: ./.github/scripts/send-advisory.py --auto
