name: Send advisory

on:
  push:
    branches: ['main']


env: # sendgrid api token
  sendgrid_api: ${{ secrets.SENDGRID_API }}

permissions:
  contents: read

jobs:
  send-modified-files:
    name: Send advisory files created in last hour
    runs-on: ubuntu-latest
    environment:
      name: communication
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout docs
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
            fetch-depth: 2
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Send advisories
        run: ./.github/scripts/send-advisory.py --auto
