name: Send advisory

on:
  push:
    branches: ['main']


env: # sendgrid api token
  sendgrid_api: ${{ secrets.SENDGRID_API }}

permissions:
  contents: read

jobs:
  send-modified-files:
    name: Send advisory files created in last hour
    runs-on: ubuntu-latest
    environment:
      name: communication
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout docs
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 2
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Send advisories
        run: ./.github/scripts/send-advisory.py --auto
